language: node_js
dist: trusty
sudo: required
node_js: 6
install:
  - npm install -g bower
  - npm install
script:
  - bower install --production
  - npm run -s build
  - bower install
  - npm -s test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
